export const ADD_WORKSPACE = 'ADD_WORKSPACE';
export const REMOVE_WORKSPACE = 'REMOVE_WORKSPACE';
export const SET_ACTIVE = 'SET_ACTIVE';
export const UPDATE_WORKSPACE_TITLE = 'UPDATE_WORKSPACE_TITLE';
